config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin', to: 'home#index'
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
  resources :categories
  resources :tags
  resources :comments, only: [:create]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags

  validates :name, presence: true, length: { maximum: 255 }

  def self.names_and_ids
    self.all.map do |tag|
      [tag.name, tag.id]
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags = Tag.page(params[:page])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save!

    flash[:success] = 'タグを作成しました。'

    redirect_to action: :index
  rescue
    render 'new'
  end

  def show
    @tag = find_tag(params)
  rescue
    redirect_to action: :index
  end

  def edit
    @tag = find_tag(params)
  rescue
    redirect_to action: :index
  end

  def update
    @tag = find_tag(params)

    update_service.update!(@tag, tag_params)

    flash[:success] = 'タグを更新しました。'

    redirect_to action: :show
  rescue
    render 'edit'
  end

  def destroy
    @tag = find_tag(params)
    @tag.destroy!

    flash[:success] = 'タグを削除しました。'
  rescue
    flash[:error] = 'タグの削除に失敗しました。'
  ensure
    redirect_to action: :index
  end

  private

  def find_tag(params)
    Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

  def update_service
    @tag_service ||= TagService::UpdateService.new
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<% if @tag.errors.any? %>
    <div class="card-panel red white-text">
      <ul>
        <% @tag.errors.full_messages.each do |m| %>
            <li><%= m %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @tag, method: method, class: 'col s12' do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :name, class: 'blue-text' %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <%= f.submit button_title, class: 'btn-large waves-effect waves-light blue' %>
      </div>
    </div>
<% end %>

app/views/tags/edit.html.erb
<h1 class="blue-text">
  タグ編集
</h1>

<div class="row">
  <%= render partial: 'form', locals: { method: 'PATCH', button_title: '適用' } %>
</div>

<div class="row">
  <%= link_to 'タグ一覧', tags_path, class: 'first-link' %>
  <%= link_to 'タグ詳細', tag_path(@tag) %>
</div>

app/views/tags/index.html.erb
<h1 class="blue-text">
  タグ
</h1>
<a href="<%= new_tag_path %>"
   class="btn-floating btn-large waves-effect waves-light green right"
   title="タグ作成">
  <i class="material-icons">
    add
  </i>
</a>
<table class="highlight">
  <thead>
  <tr>
    <th><%= I18n.t('activerecord.attributes.tag.name') %></th>
    <th><%= I18n.t('activerecord.attributes.tag.created_at') %></th>
  </tr>
  </thead>
  <tbody>
  <% @tags.each do |tag| %>
      <tr>
        <td>
          <%= link_to tag.name, tag_path(tag) %>
        </td>
        <td>
          <%= I18n.l(tag.created_at) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="center">
  <%= paginate @tags %>
</div>

app/views/tags/new.html.erb
<h1 class="blue-text">
  タグ作成
</h1>
<div class="row">
  <%= render partial: 'form', locals: { method: 'POST', button_title: '追加' } %>
</div>

app/views/tags/show.html.erb
<h1 class="blue-text">
  タグ詳細
</h1>
<div class="row">
  <div class="col s3">
    <%= I18n.t('activerecord.attributes.tag.name') %>
  </div>
  <div class="col s9">
    <%= @tag.name %>
  </div>
</div>
<div class="row">
  <div class="col s3">
    <%= I18n.t('activerecord.attributes.tag.created_at') %>
  </div>
  <div class="col s9">
    <%= I18n.l(@tag.created_at) %>
  </div>
</div>
<div class="row">
  <div class="col s3">
    <%= I18n.t('activerecord.attributes.tag.updated_at') %>
  </div>
  <div class="col s9">
    <%= I18n.l(@tag.updated_at) %>
  </div>
</div>

<div class="row">
  <%= link_to '編集', edit_tag_path(@tag), class: 'btn-large waves-effect waves-light blue first-link left' %>
  <div class="left">
    <%= form_for @tag, method: 'DELETE' do |f| %>
        <%= f.submit '削除', class: 'btn-large waves-effect waves-light red lighten-2' %>
    <% end %>
  </div>
</div>

<div class="row">
  <%= link_to 'タグ一覧', tags_path %>
</div>