config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin', to: 'home#index'
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
  resources :categories
  resources :tags
  resources :comments, only: [:create]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { maximum: 255 }

  def self.names_and_ids
    self.all.map do |category|
      [category.name, category.id]
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save!

    flash[:success] = 'カテゴリーを作成しました。'

    redirect_to action: :index
  rescue
    render 'new'
  end

  def show
    @category = find_category(params)
  rescue
    redirect_to action: :index
  end

  def edit
    @category = find_category(params)
  rescue
    redirect_to action: :index
  end

  def update
    @category = find_category(params)

    update_service.update!(@category, category_params)

    flash[:success] = 'カテゴリーを更新しました。'

    redirect_to action: :show
  rescue
    render 'edit'
  end

  def destroy
    @category = find_category(params)
    @category.destroy!

    flash[:success] = 'カテゴリーを削除しました。'
  rescue
    flash[:error] = 'カテゴリーの削除に失敗しました。'
  ensure
    redirect_to action: :index
  end

  private

  def find_category(params)
    Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def update_service
    @update_service ||= CategoryService::UpdateService.new
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
    <div class="card-panel red white-text">
      <ul>
        <% @category.errors.full_messages.each do |m| %>
            <li><%= m %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @category, method: method, class: 'col s12' do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :name, class: 'blue-text' %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <%= f.submit button_title, class: 'btn-large waves-effect waves-light blue' %>
      </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="blue-text">
  カテゴリー編集
</h1>

<div class="row">
  <%= render partial: 'form', locals: { method: 'PATCH', button_title: '適用' } %>
</div>

<div class="row">
  <%= link_to 'カテゴリー一覧', categories_path, class: 'first-link' %>
  <%= link_to 'カテゴリー詳細', category_path(@category) %>
</div>

app/views/categories/index.html.erb
<h1 class="blue-text">
  カテゴリー
</h1>
<a href="<%= new_category_path %>"
   class="btn-floating btn-large waves-effect waves-light green right"
   title="カテゴリー作成">
  <i class="material-icons">
    add
  </i>
</a>
<table class="highlight">
  <thead>
  <tr>
    <th><%= I18n.t('activerecord.attributes.category.name') %></th>
    <th><%= I18n.t('activerecord.attributes.category.created_at') %></th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td>
          <%= link_to category.name, category_path(category) %>
        </td>
        <td>
          <%= I18n.l(category.created_at) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="center">
  <%= paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1 class="blue-text">
  カテゴリー作成
</h1>
<div class="row">
  <%= render partial: 'form', locals: { method: 'POST', button_title: '追加' } %>
</div>

app/views/categories/show.html.erb
<h1 class="blue-text">
  カテゴリー詳細
</h1>
<div class="row">
  <div class="col s3">
    <%= I18n.t('activerecord.attributes.category.name') %>
  </div>
  <div class="col s9">
    <%= @category.name %>
  </div>
</div>
<div class="row">
  <div class="col s3">
    <%= I18n.t('activerecord.attributes.category.created_at') %>
  </div>
  <div class="col s9">
    <%= I18n.l(@category.created_at) %>
  </div>
</div>
<div class="row">
  <div class="col s3">
    <%= I18n.t('activerecord.attributes.category.updated_at') %>
  </div>
  <div class="col s9">
    <%= I18n.l(@category.updated_at) %>
  </div>
</div>

<div class="row">
  <%= link_to '編集', edit_category_path(@category), class: 'btn-large waves-effect waves-light blue first-link left' %>
  <div class="left">
    <%= form_for @category, method: 'DELETE' do |f| %>
        <%= f.submit '削除', class: 'btn-large waves-effect waves-light red lighten-2' %>
    <% end %>
  </div>
</div>

<div class="row">
  <%= link_to 'カテゴリー一覧', categories_path %>
</div>