config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin', to: 'home#index'
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
  resources :categories
  resources :tags
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
  has_many :article_comments, dependent: :destroy
  has_many :comments, through: :article_comments

  accepts_nested_attributes_for :article_categories
  accepts_nested_attributes_for :article_tags

  validates :title, presence: true, length: { maximum: 100  }
  validates :body,  presence: true, length: { maximum: 5000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

  validates :article,  presence: true
  validates :category, presence: true
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :comment

  validates :article, presence: true
  validates :comment, presence: true, uniqueness: true
end

app/models/article_comment_assoc.rb
class ArticleCommentAssoc < ApplicationRecord
  self.table_name = :article_comment_assoc
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag

  validates :article, presence: true
  validates :tag,     presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { maximum: 255 }

  def self.names_and_ids
    self.all.map do |category|
      [category.name, category.id]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one :article_comment, dependent: :destroy
  has_one :article, through: :article_comment
  has_many :parent_assocs,   foreign_key: 'child_id', class_name: 'CommentAssoc'
  has_many :children_assocs, foreign_key: 'parent_id',  class_name: 'CommentAssoc'
  has_one  :parent_comment, through: :parent_assocs, source: :parent_comment
  has_many :child_comments, through: :children_assocs, source: :child_comment

  validates :username, presence: true, length: { maximum: 64   }
  validates :body,     presence: true, length: { maximum: 1000 }
end

app/models/comment_assoc.rb
class CommentAssoc < ApplicationRecord
  belongs_to :parent_comment, class_name: 'Comment', foreign_key: :parent_id
  belongs_to :child_comment,  class_name: 'Comment', foreign_key: :child_id

  validates :parent_comment, presence: true
  validates :child_comment,  presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags

  validates :name, presence: true, length: { maximum: 255 }

  def self.names_and_ids
    self.all.map do |tag|
      [tag.name, tag.id]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = index_service.articles(params)

    @category_ids = index_service.category_ids || []
    @tag_ids      = index_service.tag_ids || []

    @categories = Category.names_and_ids
    @tags       = Tag.names_and_ids
  end

  def new
    @article = Article.new

    @article.article_categories.build
    @article.article_tags.build

    @categories = Category.names_and_ids
    @tags       = Tag.names_and_ids
  end

  def create
    @article = Article.new(article_params)

    ActiveRecord::Base.transaction do
      @article.save!

      create_service.create_categories!(params, @article)

      create_service.create_tags!(params, @article)
    end

    flash[:success] = '記事を作成しました。'

    redirect_to action: :index
  rescue
    @categories = Category.names_and_ids
    @tags       = Tag.names_and_ids

    render 'new'
  end

  def show
    @article = find_article(params)

    @comment  = Comment.new

    @comments_count = ArticleComment.where(article_id: @article.id).count

    @comments = Comment.includes(:article_comment).
        where(article_comments: { article_id: @article.id }).
        where.not(id: CommentAssoc.pluck(:child_id))

    @reply_comments = ArticleCommentAssoc.
        where(article_id: @article.id).
        where.not(parent_id: nil)
  rescue
    redirect_to action: :index
  end

  def edit
    @article = find_article(params)

    @categories = Category.names_and_ids
    @tags       = Tag.names_and_ids
  rescue
    redirect_to action: :index
  end

  def update
    @article = find_article(params)

    ActiveRecord::Base.transaction do
      update_service.update!(@article, article_params)

      update_service.destroy_categories(@article)
      create_service.create_categories!(params, @article)

      update_service.destroy_tags(@article)
      create_service.create_tags!(params, @article)
    end

    flash[:success] = '記事を更新しました。'

    redirect_to action: :show
  rescue
    @categories = Category.names_and_ids
    @tags       = Tag.names_and_ids

    render 'edit'
  end

  def destroy
    @article = find_article(params)
    @article.destroy!

    flash[:success] = '記事を削除しました。'
  rescue
    flash[:error] = '記事の削除に失敗しました。'
  ensure
    redirect_to action: :index
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def find_article(params)
    Article.find(params[:id])
  end

  def create_service
    @create_service ||= ArticleService::CreateService.new
  end

  def update_service
    @update_service ||= ArticleService::UpdateService.new
  end

  def index_service
    @index_service ||= ArticleService::IndexService.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags = Tag.page(params[:page])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save!

    flash[:success] = 'タグを作成しました。'

    redirect_to action: :index
  rescue
    render 'new'
  end

  def show
    @tag = find_tag(params)
  rescue
    redirect_to action: :index
  end

  def edit
    @tag = find_tag(params)
  rescue
    redirect_to action: :index
  end

  def update
    @tag = find_tag(params)

    update_service.update!(@tag, tag_params)

    flash[:success] = 'タグを更新しました。'

    redirect_to action: :show
  rescue
    render 'edit'
  end

  def destroy
    @tag = find_tag(params)
    @tag.destroy!

    flash[:success] = 'タグを削除しました。'
  rescue
    flash[:error] = 'タグの削除に失敗しました。'
  ensure
    redirect_to action: :index
  end

  private

  def find_tag(params)
    Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

  def update_service
    @tag_service ||= TagService::UpdateService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbs4b</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <%= link_to '掲示板', articles_path, class: 'brand-logo center' %>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li>
              <%= link_to '記事', articles_path %>
            </li>
            <% if user_signed_in? %>
            <li>
              <%= link_to 'カテゴリー', categories_path %>
            </li>
            <li>
              <%= link_to 'タグ', tags_path %>
            </li>
            <% end %>
          </ul>
          <ul id="nav-mobile" class="left show-on-medium-and-down hide-on-large-only">
            <li>
              <a href="<%= articles_path %>" title="記事">
                <i class="fa fa-file-text-o"></i>
              </a>
            </li>
            <% if user_signed_in? %>
            <li>
              <a href="<%= categories_path %>" title="カテゴリー">
                <i class="fa fa-pie-chart"></i>
              </a>
            </li>
            <li>
              <a href="<%= tags_path %>" title="タグ">
                <i class="fa fa-tag"></i>
              </a>
            </li>
            <% end %>
          </ul>


          <ul class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li>
                <%= link_to '設定', admin_path %>
              </li>
            <% end %>
            <li>
              <% if user_signed_in? %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
              <% else %>
                <%= link_to 'ログイン', new_session_path(:user) %>
              <% end %>
            </li>
          </ul>
          <ul class="right show-on-medium-and-down hide-on-large-only">
            <% if user_signed_in? %>
              <li>
                <a href="<%= admin_path %>" title="設定">
                  <i class="fa fa-cog"></i>
                </a>
              </li>
            <% end %>
            <li>
              <% if user_signed_in? %>
                <a href="<%= destroy_user_session_path %>" data-method="delete" title="ログアウト">
                  <i class="fa fa-sign-out"></i>
                </a>
              <% else %>
                <a href="<%= new_session_path(:user) %>" title="ログイン">
                  <i class="fa fa-sign-in"></i>
                </a>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <% if flash.any? %>
        <div class="card-panel blue lighten-2 white-text">
          <% flash.each do |k, v| %>
            <%= v %>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>